version: "3"
services:
  server:
    build: ./email-api
    expose:
      - 4000
    environment:
      - API_HOST=http://localhost:4000
      - APP_SERVER_PORT=4000
    ports:
      - 4000:4000
    volumes:
      - ./email-api/src:/usr/src/email-api/src
    command: node index.js
  client:
    build: ./email-app
    environment:
      - REACT_APP_PORT=3000
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./email-app/src:/usr/src/email-app/src
      - ./email-app/public:/usr/src/email-api/public
    links:
      - server
    command: yarn start
