version: "3"
services:
  server:
    build: ./email-api
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./email-api/src:/usr/src/email-api/src
    command: node index.js
  client:
    build: ./email-app
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./email-app/src:/usr/src/email-app/src
      - ./email-app/public:/usr/src/email-api/public
    links:
      - server
    command: yarn start
